# ده ملف تحسين الأداء وتجاهل الأخطاء غير الضرورية
include: package:flutter_lints/flutter.yaml

analyzer:
  # تجاهل الملفات اللي بتعمل مشاكل في الـ CI
  exclude:
    - test/**
    - "**.g.dart"
    - "**.freezed.dart"

  errors:
    # طنش تحذيرات الـ withOpacity والـ WillPopScope عشان الـ Build يكمل
    deprecated_member_use: ignore
    # طنش أي مشاكل في التيست لو الملف موجود
    creation_with_non_type: ignore
    # طنش التحذيرات التانية عشان الـ CI يكمل
    curly_braces_in_flow_control_structures: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    use_build_context_synchronously: ignore
    library_private_types_in_public_api: ignore
    use_key_in_widget_constructors: ignore

linter:
  rules:
    # تقدر تضيف هنا أي قواعد زيادة تحبها
    avoid_print: false # عشان لو سايب print في الكود ميعطلش الـ Build